---
- name: "Install zsh packages and fonts"
  apt:
    name: 
      [
        "zsh",
        "zsh-common",
        "zsh-doc",
        "fonts-noto",
        "fonts-powerline",
        "fonts-firacode"
      ]
    state: latest
  become: yes

- name: "Clone ohmyzsh repository"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "/tmp/ohmyzsh"
  become: no

- name: "Uninstall previus ohmyzsh installation"
  shell:
    cmd: "yes | sh /tmp/ohmyzsh/tools/uninstall.sh"
  become: no

- name: "Install ohmyzsh package"
  shell:
    cmd: "sh /tmp/ohmyzsh/tools/install.sh --unattended"
  become: no

- name: "Install antigen package"
  shell:
    cmd: "curl -L git.io/antigen > $HOME/.antigen.zsh"
  become: no

- name: "Edit .antigen.zsh"
  replace:
    path: $HOME/.antigen.zsh
    regexp: 'antigen\.zsh'
    replace: '.antigen.zsh'
  become: no


- name: "Install zsh-completions"
  git:
    repo: "https://github.com/zsh-users/zsh-completions"
    dest: "$HOME/.oh-my-zsh/custom/plugins/zsh-completions"
  become: no

- name: "Copy .zshrc"
  copy:
    src: ".zshrc"
    dest: "$HOME"
  become: no

- name: "Create project directory"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - $HOME/Documents/projects
    - $HOME/Documents/projects/git
    - $HOME/Documents/projects/git/ufms
  become: no

- name: "Change default user shell to zsh"
  user:
    name: "{{ default_user }}"
    shell: /usr/bin/zsh
  become: yes