---
- name: "Install dropbox Package"
  apt:
    deb: "https://linux.dropbox.com/packages/ubuntu/dropbox_2020.03.04_amd64.deb"
  become: yes

- name: "Install dependences"
  apt:
    name: "python3-gpg"
  become: yes