---
# Ubuntu
- name: Add spotify GPG apt-key
  apt_key:
    url: "https://download.spotify.com/debian/pubkey_0D811D58.gpg"
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add spotify repository
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install spotify
  apt:
    name: spotify-client
    update_cache: yes
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'
